### ISSUE TITLE
Make tests more independent

### ISSUE THREAD

**Issue by ghost** [cadet/CADET-Python#2]
Currently, the tests and examples are not platform independent and also include hard coded references to files which are not included in the repository. Maybe this could be improved.

**Comment by schmoelder** [comment]
Just for clarification, I accidentally posted this issue with an old user account of mine (chromapy) which I have deleted in the meantime.

**Comment by schmoelder** [comment]
done in 026f18e1c077b88c77c83728b9e38e97b891b5e7
