### ISSUE TITLE
Fix multi-threading PicklingError

### ISSUE THREAD

**Issue by jbreue16** [cadet/CADET-Python#25]
Updating to cadet-python v1.0.0 in cadet-verification, the parallelization code using joblib was broken with the error `PicklingError: Could not pickle the task to send it to the workers.`

A MRE is [here](https://gist.github.com/jbreue16/6bc2ef4f666ca57f54ab25dfdd531ac8)
The old version does nothing for the above code since the input to the modle is nonsense
The new cadet-python version gives the aforementioned error

**Comment by schmoelder** [comment]
For convenience, here's the even more MRE:
```
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 15 14:47:04 2024

@author: js
"""

from cadet import Cadet
from joblib import Parallel, delayed
import platform
from pathlib import Path
import shutil

n_jobs = 2


def run_simulation(model):
    model.save()
    data = model.run_load()


model1 = Cadet()
model1.root.input = { 'model' : 1 }
model1.filename = "jo"
model2 = Cadet()
model2.root.input = { 'model' : 2 }
model2.filename = "jojo"

sims = [model1, model2]

# %%

for sim in sims:
    run_simulation(sim)


# %%
backend = Parallel(n_jobs=n_jobs, verbose=0)
backend(
        delayed(run_simulation)(sim) for sim in zip(sims)
)
```

**Comment by ronald-jaepel** [comment]
This is because we can not pickle c pointers. 

My proposed solution in #26 is to remove all pointers from the state, only save the `_cadet_path` and then on __getstate__ re-load the dll and pointers in the child-thread.
